name: vexana
description: flutter network helper project..
version: 1.1.5+2
homepage: https://github.com/VB10/vexana

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  path_provider_platform_interface: ^1.0.1
  plugin_platform_interface: ^1.0.2
